### ISSUE TITLE
Pre_parser - username

### ISSUE THREAD

**Issue by ceqa** [formtools/module-submission_pre_parser#10]
Hello,
I need the username to be entered automatically in the form without the possibility to edit it (same as in the case of IP address, ID, creation date, etc.) Would anyone be able to tell me how I can do it. It is possible at all?

**Comment by ceqa** [comment]
So far, I managed to create something like that. 
`
$db = FormTools\Core::$db;

$db->query("SELECT `cd_create` FROM `ft_form_1` WHERE `submission_id` = 1");
$db->execute();
$rows = $db->fetchAll();

foreach ($rows as $row) {
    print_r($row['cd_create']);
}
`
I have two problems now. How to take a username from the session? and secondly how to put this value in the HTML?

**Comment by benkeen** [comment]
Hi @ceqa, I'm so sorry for not responding sooner - I'm actually adding this very feature in 3.0.13. It's already completed locally, I just need to get a few more things done before releasing it. 

Basically all you'll need to do is add a placeholder in the "Default Values for New Submissions" field under Edit Form -> Edit View -> main tab, like `{$USERNAME}` and all new submissions created within Form Tools will get that value added to a field. You can then edit that field in your view(s) to make sure it's not editable. 

Time-wise it's a little tricky to estimate - I only get time in the evenings & weekends to work on this & I may be out of town this weekend. But I'll post back here when I get more info. 

Regarding your Submission Pre-Parser solution, correct! That's always been the solution up until now. 

Regarding your question, you can find the username in sessions here:`FormTools\Sessions::get("account.username");`.

I think to put it into the form you'll need to add it to $_POST["your_field_name"]... but I'm not positive (sorry, very late - must run).

**Comment by ceqa** [comment]
Hi @benkeen thanks for reply! I have quick question regarding the solution you suggested. How do you think I should write it in the screen below?

![obraz](https://user-images.githubusercontent.com/15996656/52697385-a5253600-2f71-11e9-9d99-c794241c7f4e.png)

Secondly i should to create new custom field? Somethink like this `<input type="input" name="{$NAME}" id="{$NAME}_id" class="cf_userfield {$class}"
    value="{$USERNAME}" />`? But the value from `account.username` i should define in Pre-Parser module? Thanks a lot for help!

**Comment by benkeen** [comment]
Actually the solution I mentioned for that section won't work yet - I'm still working on 3.0.13, but all you'll need to do is select a field in that dropdown, then add `{$USERNAME}` in the Default Value field and all new submissions created in the FT interface will get the username of the user (admin/client). Until that's released you have to use the Submission Pre-Parser method to populate a value into $_POST that corresponds to the field name where you want to store the data.

And no, I wouldn't mess with the Custom Fields module. Neat idea though! But no, it wouldn't work for just initializing the field with a particular value - it would always overwrite it for any page loads.

**Comment by ceqa** [comment]
It should look like?
`$username =  FormTools\Sessions::get("account.username");
if (!empty($_POST["username"])) {
  $_POST[$username] = true;
}`

**Comment by ceqa** [comment]
@benkeen I know that you are very busy person but maybe you have time to answear my question. How I can (in detail) insert a value from `$username` to `<input value= />`

**Comment by ceqa** [comment]
Everythink what I have now is define in Submission Pre-Parser module `$username = FormTools\Sessions::get("account.username"); ` and in Custom Fields module define 
```
<input type="text" name="{$NAME}" value="<?php echo $username; ?>" class="{$size}{if $highlight} {$highlight}{/if}" id="username"
  onblur="przyjecie();"
  {if $maxlength}maxlength="{$maxlength}"{/if} />
  {if $comments}
    <div class="cf_field_comments">{$comments}</div>
  {/if}
```

But this solution doesn't working...

**Comment by ceqa** [comment]
Now I try somethink like this in Submission Pre-Parser module:

`if (!empty($_POST["username"])) {
    $_POST["FormTools\Sessions::get("account.username")"] = true;
} `

and in Custom Fields module define:

`<input type="text" name="{$NAME}" value="<?php echo $username ?>" class="{$size}{if $highlight} {$highlight}{/if}" id="username" 
{if $maxlength}maxlength="{$maxlength}"{/if} />`

but i have value `<?php echo $username ?>`

**Comment by ceqa** [comment]
Problem solved!
The reason was add in config.php `$g_use_smarty_bc = true;` and nextly in Custom Fields modules 

`{php}
$username = FormTools\Sessions::get("account.username");
{/php}

<input readonly type="text" name="{$NAME}" value="{php}echo $username{/php}" class="" id="username"
  {if $maxlength}maxlength="{$maxlength}"{/if} />
  {if $comments}
    <div class="cf_field_comments">{$comments}</div>
  {/if}
`
