### ISSUE TITLE
Select and Update other form id submissions?

### ISSUE THREAD

**Issue by johnbleck3** [formtools/module-submission_pre_parser#3]
Ben -In the documentation it's clear on how to gather and change information supplied in the submission of the form being entered by the user and I used it quite a bit in 2.0.
In the 2.0 version, I've selected and updated other forms outside the $_POST values via pre-parser using mysql_query. 
Example: I'm on form 5 but I need to pull data from form 10 when a submission is updated based on $_POST values on form 5 and pull data from form 10 into the submission in form 5.
Will I still be able to do this? Any chance I could get a little example selecting another form using PDO in the preparser? Or is the scope of pre-parser's reach now limited to the $_POST values?

**Comment by benkeen** [comment]
Oh sure, no worries! Maybe I'll add a page explaining this to the doc - seems pretty useful.

The syntax has all changed with PDO, but the functionality is all still possible. Here's a few examples. Basically you need to first get the PDO object, stashed as a public member var within the Core class, then execute queries on it. The syntax is a bit odd at first, but not having to manually escape everything is an absolute delight. ;)

You can just add this right into your Submission Pre-Parser rule.

```php
// grab our PDO $db object
$db = FormTools\Core::$db;

// this defines a query, executes it, then grabs all the results
$db->query("SELECT * FROM abc_form_5");
$db->execute();
$rows = $db->fetchAll();

// outputs the number of rows in the above query, kinda handy
echo $db->numRows();
  
// loop through each and output the array
foreach ($rows as $row) {
  print_r($row);
}

// passing vars is done via placeholders, like so:
$db->query("SELECT * FROM abc_form_63 WHERE submission_id = :submission_id");
$db->bind("submission_id", 1);
$db->execute();

// fetching a single submission
$submission = $db->fetch();
```

**Comment by johnbleck3** [comment]
Awesome. Very glad to hear, and those examples were exactly what I needed.  Thank you!

**Comment by benkeen** [comment]
No problem! I updated the doc here. It's a starting-point at least, in case anyone needs DB interaction.
https://docs.formtools.org/modules/submission_pre_parser/database_access/
